- name: installing apache and running the backend
  hosts: server_2
  become: yes
  tasks:
    - name: installing apache
      apt:
        name:
          - apache2
          - php
          - libapache2-mod-php
        state: latest
        update_cache: yes

    - name: running the service
      service:
        name: apache2
        state: started
        enabled: yes

    - name: copying the PHP backend file
      copy:
        src: index.php
        dest: /var/www/html/

    - name: copying the JS file
      copy:
        src: form-handler.js
        dest: /var/www/html/
